repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/JohnnyMorganz/StyLua
  rev: v0.12.1
  hooks:
  - id: stylua-system
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.1
  hooks:
  - id: shellcheck
    args:
    - --shell=bash
- repo: local
  hooks:
  - id: luacheck
    name: luacheck
    entry: luacheck
    language: system
    types: [lua]
  - id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    require_serial: true
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
