---
name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        repository: ferronn-dev/addonmaker
        tags: latest
        tag_with_sha: true
        username: ferronn-dev
