---
name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: docker/build-push-action@v1
      with:
        cache_froms: ghcr.io/ferronn-dev/addonmaker:latest
        password: ${{ secrets.CR_PAT }}
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        registry: ghcr.io
        repository: ferronn-dev/addonmaker
        tags: latest
        tag_with_sha: true
        username: ferronn-dev
