---
name: build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ferronn-dev
        password: ${{ secrets.CR_PAT }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Checkout (GitHub)
      uses: actions/checkout@v2
    - name: Build and test in devcontainer
      uses: devcontainers/ci@v0.2
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ghcr.io/ferronn-dev/addonmaker:latest
